name: Workflow with Email Identifier

on:
  # Runs when manually triggered
  workflow_dispatch:
  # Also runs on push to main branch
  push:
    branches: [ main ]

jobs:
  hello-world:22f2000536@ds.study.iitm.ac.in
    runs-on: ubuntu-latest
    
    steps:
      - name: 
        run: echo "Hello, world!"
        
      - name: Display date
        run: date
